// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { mockAuth, MockQueryBuilder } from './mock-client';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    import.meta.env['VITE_SUPABASE_URL'] ||
    process.env['SUPABASE_URL'] ||
    'https://tisxysjscvbdbewdjkdk.supabase.co';
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] ||
    process.env['SUPABASE_PUBLISHABLE_KEY'] ||
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpc3h5c2pzY3ZiZGJld2Rqa2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDAwMDAwMDAsImV4cCI6MjAxNTAwMDAwMH0.placeholder';

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storageKey: 'dayflow_auth_session',
      storage: typeof window !== 'undefined' ? window.sessionStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

function isDemoSessionActive(): boolean {
  if (typeof window === 'undefined') return false;
  return !!(sessionStorage.getItem('dayflow_demo_session') || localStorage.getItem('dayflow_demo_session'));
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();

    if (prop === 'auth') {
      const realAuth = _supabase.auth;
      return new Proxy(realAuth, {
        get(target, authProp) {
          if (authProp === 'getSession') {
            return async () => {
              const demo = await mockAuth.getSession();
              if (demo.data?.session) return demo;
              try {
                const res = await target.getSession();
                if (res.data?.session) return res;
                return demo;
              } catch {
                return demo;
              }
            };
          }
          if (authProp === 'getUser') {
            return async () => {
              const demo = await mockAuth.getUser();
              if (demo.data?.user) return demo;
              try {
                const res = await target.getUser();
                if (res.data?.user) return res;
                return demo;
              } catch {
                return demo;
              }
            };
          }
          if (authProp === 'signInWithPassword') {
            return async (credentials: any) => {
              try {
                const res = await target.signInWithPassword(credentials);
                if (res.error) {
                  return await mockAuth.signInWithPassword(credentials);
                }
                return res;
              } catch {
                return await mockAuth.signInWithPassword(credentials);
              }
            };
          }
          if (authProp === 'signUp') {
            return async (credentials: any) => {
              try {
                const res = await target.signUp(credentials);
                if (res.error) {
                  return await mockAuth.signUp(credentials);
                }
                return res;
              } catch {
                return await mockAuth.signUp(credentials);
              }
            };
          }
          if (authProp === 'signOut') {
            return async () => {
              await mockAuth.signOut();
              try {
                return await target.signOut();
              } catch {
                return { error: null };
              }
            };
          }
          return Reflect.get(target, authProp);
        },
      });
    }

    if (prop === 'from') {
      return (table: string) => {
        if (isDemoSessionActive()) {
          return new MockQueryBuilder(table);
        }
        const realQuery = _supabase!.from(table as any);
        return new Proxy(realQuery, {
          get(target, queryProp, r) {
            const original = Reflect.get(target, queryProp, r);
            if (typeof original === 'function') {
              return (...args: any[]) => {
                const res = original.apply(target, args);
                if (res && typeof res.then === 'function') {
                  return new Proxy(res, {
                    get(promiseTarget, promiseProp) {
                      if (promiseProp === 'then') {
                        return (onFulfilled: any, onRejected: any) => {
                          return promiseTarget.then(async (val: any) => {
                            if (val?.error) {
                              // Fall back to mock builder on DB query error
                              const mockRes = await new MockQueryBuilder(table).then(
                                (m: any) => m
                              );
                              return onFulfilled ? onFulfilled(mockRes) : mockRes;
                            }
                            return onFulfilled ? onFulfilled(val) : val;
                          }, async (err: any) => {
                            const mockRes = await new MockQueryBuilder(table).then(
                              (m: any) => m
                            );
                            return onFulfilled ? onFulfilled(mockRes) : mockRes;
                          });
                        };
                      }
                      return Reflect.get(promiseTarget, promiseProp);
                    }
                  });
                }
                return res;
              };
            }
            return original;
          }
        });
      };
    }

    return Reflect.get(_supabase, prop, receiver);
  },
});
